In [1]:
import openpyxl
import os
import shutil #python copy model
import numpy as np
import math
import csv
import pandas as pd
from openpyxl import load_workbook

In [2]:
# 計算兩點距離
def eucliDist(A,B):
    return math.sqrt(sum([(a - b)**2 for (a,b) in zip(A,B)]))

In [3]:
#計算角度
def sita(a,b,c):
    if(a+b>c and a+c>b and b+c>a):    #判断三边是否能构成三角形
         A = math.degrees(math.acos((a*a-b*b-c*c)/(-2*b*c)))     #求角A
         B = math.degrees(math.acos((b*b-a*a-c*c)/(-2*a*c)))  #求角B
         C = math.degrees(math.acos((c*c-a*a-b*b)/(-2*a*b)))  #求角C
         return(A,B,C)      #输出角A #输出角B #输出角C
    else:
        #print("三边无法构成三角形")
        return(0,0,0)

In [4]:
def CAandDis(fileNameIn,fileNameOut_CA,fileNameOut_Dis):
    #輸入路徑!!!!!!!!!!
    wb = load_workbook(fileNameIn)
    sheet = wb.active
    
    #整行資料儲存轉成list
    X_data = []
    for cell in list(sheet.columns)[13]:
        X_data.append(cell.value)

    Y_data = []
    for cell in list(sheet.columns)[14]:
        Y_data.append(cell.value)

    frame=[]
    for cell in list(sheet.columns)[9]:
        frame.append(cell.value)
    
    #建立CA.csv
    with open(fileNameOut_CA, 'w', newline = '') as csvFile:
        csvWriter = csv.writer(csvFile)
        csvWriter.writerow(['frame', 'ReyeX', 'ReyeY', 'LeyeX', 'LeyeY', 'RearX', 'RearY', 'LearX', 'LearY', 'noseX', 'noseY'])

    Num=int((len(X_data)-1)/5)
    for i in range(int(Num)):
        #未旋轉 
        (x1, y1)=(X_data[i+1], Y_data[i+1])
        (x2, y2)=(X_data[i+Num+1], Y_data[i+Num+1])
        (x3, y3)=(X_data[i+2*Num+1], Y_data[i+2*Num+1])
        (x4, y4)=(X_data[i+3*Num+1], Y_data[i+3*Num+1])
        (x5, y5)=(X_data[i+4*Num+1], Y_data[i+4*Num+1])
        
        #寫入CA.csv
        with open(fileNameOut_CA, 'a+', newline = '') as csvFile:
            csvWriter = csv.writer(csvFile)
            csvWriter.writerow([frame[i+1], x1, y1, x2, y2, x3, y3, x4, y4, x5, y5])
    
    #讀入CA.csv
    CA=pd.read_csv(fileNameOut_CA).values
    
    #建立Dis.csv
    with open(fileNameOut_Dis, 'w', newline = '') as csvFile:
        csvWriter = csv.writer(csvFile)
        csvWriter.writerow(['frame', 'eyes', 'eyeRearR', 'eyeRearL', 'eyeRnose', 'eyeLearR', 'eyeLearL', 'eyeLnose', 'ears'])  

    #計算歐式距離
    for i in CA:
        Q1=i[1:3];Q2=i[3:5];Q3=i[5:7];Q4=i[7:9];Q5=i[9:11];
        d=eucliDist(Q1,Q2);
        d1=eucliDist(Q1,Q3);d2=eucliDist(Q1,Q4);d3=eucliDist(Q1,Q5);
        d4=eucliDist(Q2,Q3);d5=eucliDist(Q2,Q4);d6=eucliDist(Q2,Q5);
        d7=eucliDist(Q3,Q4);
        
        #寫入Distance.csv
        with open(fileNameOut_Dis, 'a+', newline = '') as csvFile:
            csvWriter = csv.writer(csvFile)
            csvWriter.writerow([i[0] ,d, d1, d2, d3, d4, d5, d6, d7])

In [5]:
def sitaFace(fileNameIn,fileNameOut):
    #要輸入的檔名!!!!!!!!!
    D=pd.read_csv(fileNameIn).values

    #輸出檔名.csv!!!!!
    file = fileNameOut
    with open(file, 'w', newline = '') as csvFile:
        csvWriter = csv.writer(csvFile)
        csvWriter.writerow(['frame','sita1','sita2','sita3','sita4','sita5',
                            'sita6','sita7','sita8','sita9','sita10',
                            'sita11','sita12','sita13','sita14','sita15'])
    #計算角度
    for i in D:
        s=sita(i[1],i[2],i[5]);s1=sita(i[1],i[3],i[6]);s2=sita(i[1],i[4],i[7]);
        o=sita(i[8],i[2],i[3]);o1=sita(i[8],i[5],i[6]);
       
        with open(file, 'a+', newline = '') as csvFile:
            csvWriter = csv.writer(csvFile)
            csvWriter.writerow([i[0], s[0], s[1], s[2], s1[0], s1[1], s1[2], s2[0], s2[1], s2[2],
                                o[0], o[1], o[2], o1[0], o1[1], o1[2]
                               ])

In [6]:
#輸入 xlse 
#輸出CA&Dis檔名
CAandDis('health.xlsx','CoordinateAlignmentHealth.csv','DistanceHealth.csv')

In [7]:
#輸入 距離特徵 & 輸出檔名
sitaFace('DistanceHealth.csv','sitaHealth.csv' )

In [8]:
CAandDis('pain.xlsx','CoordinateAlignmentPain.csv','DistancePain.csv')
sitaFace('DistancePain.csv','sitaPain.csv')

In [9]:
CA=pd.read_csv('CoordinateAlignmentPain.csv')
CA

,frame,ReyeX,ReyeY,LeyeX,LeyeY,RearX,RearY,LearX,LearY,noseX,noseY
0,497,755,687,558,716,821,331,549,372,585,848
1,498,778,679,581,716,827,317,553,360,612,848
2,499,825,680,615,720,844,303,558,348,666,854
3,500,885,678,673,722,876,299,572,337,735,848
4,501,937,666,720,709,898,295,576,330,796,826
...,...,...,...,...,...,...,...,...,...,...,...
4756,32631,951,691,741,693,974,276,621,248,793,842
4757,32632,940,688,733,690,973,276,615,244,782,837
4758,32633,928,687,726,696,970,273,610,242,772,842
4759,32634,912,693,717,699,964,273,606,242,760,842
4760,32635,896,691,706,696,954,271,615,240,747,842

In [10]:
Dis=pd.read_csv('DistancePain.csv')
Dis

,frame,eyes,eyeRearR,eyeRearL,eyeRnose,eyeLearR,eyeLearL,eyeLnose,ears
0,497,199.123078,362.066292,376.378799,234.138848,466.255295,344.117712,134.733069,275.072718
1,498,200.444506,365.301246,390.366494,236.890270,468.739800,357.099426,135.591298,277.353565
2,499,213.775583,377.478476,426.043425,235.705325,475.741526,376.341600,143.377125,289.518566
3,500,216.517898,379.106845,462.871472,226.715681,469.188661,398.027637,140.427917,306.365794
4,501,221.219348,373.044233,493.170356,213.262749,450.643984,405.434335,139.517024,323.896588
...,...,...,...,...,...,...,...,...,...
4756,32631,210.009524,415.636861,552.402933,218.552053,477.679809,460.895867,157.813181,354.108740
4757,32632,207.009662,413.319489,550.237222,217.175045,478.535265,461.345857,154.951605,359.427322
4758,32633,202.200396,416.124981,546.945153,219.911346,488.328783,468.585104,153.075145,361.332257
4759,32634,195.092286,423.206805,545.011009,212.849712,492.427660,470.287146,149.325149,359.339672
4760,32635,190.065778,423.985849,531.377455,212.136748,492.066052,464.991398,151.647618,340.414453

In [11]:
sita = pd.read_csv('sitaPain.csv')
sita

,frame,sita1,sita2,sita3,sita4,sita5,sita6,sita7,sita8,sita9,sita10,sita11,sita12,sita13,sita14,sita15
0,497.0,23.834639,47.288099,108.877262,31.684736,83.124417,65.190847,58.117638,86.814128,35.068233,43.686415,65.388551,70.925034,35.836318,97.073288,47.090394
1,498.0,23.946895,47.707236,108.345869,30.699281,83.859937,65.440782,57.703241,87.420890,34.875868,42.905087,63.722496,73.372417,36.152701,94.421777,49.425522
2,499.0,25.888715,50.441843,103.669443,30.095390,87.927140,61.977470,63.257528,79.947623,36.794850,41.691973,60.134934,78.173094,37.485297,90.230324,52.284379
3,500.0,26.996932,52.638286,100.364782,27.848865,92.974490,59.176645,67.623780,75.524997,36.851222,41.188137,54.576550,84.235314,40.336204,82.425414,57.238381
4,501.0,29.266335,55.526287,95.207378,26.250056,99.595805,54.154140,74.394766,68.201693,37.403541,41.053238,49.149243,89.797519,44.069518,75.399299,60.531183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4756,32631.0,26.022223,60.259936,93.717841,21.591627,104.545915,53.862458,65.536385,71.307013,43.156602,39.855383,48.781588,91.363029,44.285979,70.373215,65.340806
4757,32632.0,25.521856,59.345130,95.133014,21.384038,104.265853,54.350110,65.114149,72.118616,42.767235,40.782904,48.688709,90.528387,44.920722,70.072746,65.006531
4758,32633.0,24.184934,57.471174,98.343892,21.217053,101.781708,57.001240,62.672228,75.063098,42.264675,41.342652,49.528482,89.128866,44.310533,70.745535,64.943932
4759,32634.0,23.047835,58.131928,98.820238,20.504477,101.889719,57.605803,62.307031,75.026395,42.666574,41.214434,50.894391,87.891175,43.757792,71.398868,64.843340
4760,32635.0,22.402273,58.227746,99.369981,20.639610,99.778331,59.582059,60.303940,75.821530,43.874530,39.787923,52.849717,87.362360,41.550586,73.489327,64.960087

In [12]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.utils import shuffle
from sklearn.model_selection import cross_val_score

In [13]:
dfh=pd.read_csv('DistanceHealth.csv')
dfh.insert(9,column="PainLevel",value=0)
dfh=dfh.drop(labels=['frame'],axis=1)

dfp=pd.read_csv('DistancePain.csv')
dfp.insert(9,column="PainLevel",value=1)
dfp=dfp.drop(labels=['frame'],axis=1)


#Num of pain = Num of health

if len(dfp) >= len(dfh):
    dfp=pd.DataFrame.sample(dfp,n=len(dfh),random_state=1).reset_index(drop=True)
    print(len(dfp))
elif len(dfp) < len(dfh):
    dfh=pd.DataFrame.sample(dfh,n=len(dfp),random_state=1).reset_index(drop=True)
    print(len(dfh))
    
# df of train = health+pain
df = shuffle(pd.concat([dfh,dfp]),random_state=1).reset_index(drop=True)

data = df.drop(labels=['PainLevel'],axis=1).values
target = df.PainLevel.values

4761

In [ ]:
ss = StandardScaler()
data_Standar = ss.fit_transform(data)

from sklearn.model_selection import RandomizedSearchCV
svc = svm.SVC(kernel='linear')
param_dist = {
        'C':np.linspace(0.1,1000,10000)
        }

grid = RandomizedSearchCV(svc,param_dist,cv = 3,scoring = 'accuracy',n_iter=100,n_jobs = -1,verbose=1)

grid.fit(data_Standar,target)
best_estimator = grid.best_estimator_
print(best_estimator)
print(grid.best_score_)

In [ ]:
ss = StandardScaler()
data_Standar = ss.fit_transform(data)

c_range = [0.001,0.003,0.01,0.03,0.1,0.3,1,3,10,30,100,300,1000]
c_scores = []

for c_number in c_range:
    svc = svm.SVC(C=c_number, kernel='linear',probability=True)
    scores = cross_val_score(svc,data_Standar,target,cv=3,scoring='accuracy',verbose=1,n_jobs=-1)
    c_scores.append(scores.mean())

plt.plot(c_range,c_scores)
plt.xlabel('Value of c for SVM')
plt.ylabel('Cross-Validated Accuracy')
plt.show()